apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-page
  namespace: blue
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blue-page
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: blue-page
      annotations:
        configmap.revision: "1"  # increment this number every time ConfigMap changes
    spec:
      containers:
      - name: blue-page
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: blue-page-html
