apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-page-html
  namespace: blue
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Blue Page</title>
        <style>
            body {
                background-color: blue;
                color: white;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                font-family: Arial, sans-serif;
            }
        </style>
    </head>
    <body>
        <h1>Welcome to the Blue Page!</h1>
    </body>
    </html>